import type { ViewpointProject, VisualScene } from "./types.js";

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char]!);
}

function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/-->/g, "--\\u003e");
}

function renderScene(scene: VisualScene): string {
  const byId = new Map(scene.nodes.map((node) => [node.id, node]));
  const edges = scene.edges.map((edge, index) => {
    const from = byId.get(edge.source), to = byId.get(edge.target);
    if (!from || !to) return "";
    return `<g class="vedge" data-order="${index}" data-family="${edge.family}"><line x1="${from.x}" y1="${from.y}" x2="${to.x}" y2="${to.y}"/><text x="${(from.x + to.x) / 2}" y="${(from.y + to.y) / 2 - 10}">${escapeHtml(edge.label || edge.subtype)}</text></g>`;
  }).join("");
  const nodes = scene.nodes.map((node, index) => `<g class="vnode ${node.emphasis === "strong" ? "strong" : ""}" data-order="${index}" transform="translate(${node.x - 104} ${node.y - 40})"><rect width="208" height="80" rx="18"/><text x="104" y="39" text-anchor="middle"><tspan x="104" dy="0">${escapeHtml(node.label.slice(0, 32))}</tspan>${node.label.length > 32 ? `<tspan x="104" dy="20">${escapeHtml(node.label.slice(32, 60))}</tspan>` : ""}</text><title>${escapeHtml(node.label)}</title></g>`).join("");
  return `<section class="scene" data-scene-id="${escapeHtml(scene.id)}" data-duration="${scene.durationMs}"><header><span>${escapeHtml(scene.cognitiveAction)}</span><h2>${escapeHtml(scene.title)}</h2></header><svg viewBox="0 0 ${scene.viewBox.width} ${scene.viewBox.height}" role="img" aria-label="${escapeHtml(scene.title)}"><defs><marker id="arrow-${escapeHtml(scene.id)}" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z"/></marker></defs><g class="edges" style="marker-end:url(#arrow-${escapeHtml(scene.id)})">${edges}</g><g class="nodes">${nodes}</g></svg></section>`;
}

export function generateStandaloneHtml(project: ViewpointProject): string {
  const visibleScenes = project.visualIR.scenes.filter((scene) => !scene.hidden);
  const ratio = project.settings.aspectRatio === "9:16" ? "9 / 16" : project.settings.aspectRatio === "1:1" ? "1 / 1" : "16 / 9";
  return `<!doctype html><html lang="${escapeHtml(project.ir.language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(project.ir.title)} · Viewpoint Compiler</title><style>
:root{--bg:#f5f3ee;--panel:#fffdf9;--ink:#18171c;--muted:#6d6875;--accent:#6d5ef7;--edge:#8178d8;--border:#ded9d0;font-family:Inter,"Noto Sans SC",system-ui,sans-serif}.theme-Academic{--bg:#f2f0e9;--panel:#fffefa;--ink:#182438;--accent:#315f8f;--edge:#6387aa}.theme-Social{--bg:#0f1020;--panel:#1a1b33;--ink:#fff;--muted:#aaa8cb;--accent:#ffcc4d;--edge:#ff8e72;--border:#35375b}.theme-Playful{--bg:#fff2dc;--panel:#fffaf0;--ink:#35263a;--accent:#ff5e84;--edge:#3cb9a5;--border:#efbd9b}.theme-Technical{--bg:#07110f;--panel:#0d1c18;--ink:#d7fff4;--muted:#77a89a;--accent:#2ee6a6;--edge:#53bde8;--border:#25463e}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);min-height:100vh;display:grid;place-items:center}.app{width:min(96vw,1200px);padding:22px}.brand{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.brand b{letter-spacing:.08em;text-transform:uppercase}.brand span{color:var(--muted);font-size:13px}.stage{aspect-ratio:${ratio};max-height:78vh;margin:auto;background:var(--panel);border:1px solid var(--border);border-radius:28px;overflow:hidden;box-shadow:0 22px 60px #0002;position:relative}.scene{position:absolute;inset:0;padding:24px 32px 10px;display:none}.scene.active{display:block}.scene header{position:absolute;left:34px;top:26px;z-index:2}.scene header span{font-size:11px;letter-spacing:.12em;color:var(--accent);text-transform:uppercase;font-weight:800}.scene h2{font-size:22px;margin:4px 0}.scene svg{width:100%;height:100%}.vnode rect{fill:var(--panel);stroke:var(--border);stroke-width:2}.vnode.strong rect{stroke:var(--accent);stroke-width:4;filter:drop-shadow(0 8px 12px #0002)}.vnode text{fill:var(--ink);font-size:15px;font-weight:650}.vedge line{stroke:var(--edge);stroke-width:4;stroke-linecap:round}.vedge text{fill:var(--muted);font-size:12px;text-anchor:middle}.controls{display:flex;gap:10px;align-items:center;margin-top:16px}.controls button{border:1px solid var(--border);background:var(--panel);color:var(--ink);border-radius:999px;padding:9px 15px;cursor:pointer}.controls button.primary{background:var(--accent);color:white;border-color:transparent}.progress{height:6px;background:var(--border);border-radius:999px;flex:1;overflow:hidden}.progress i{display:block;height:100%;background:var(--accent);width:0}.counter{font-variant-numeric:tabular-nums;color:var(--muted);font-size:13px}@media(max-width:700px){.app{padding:10px}.stage{border-radius:18px}.scene{padding:16px}.scene h2{font-size:16px}.vnode text{font-size:13px}}
</style></head><body class="theme-${escapeHtml(project.settings.theme)}"><main class="app"><div class="brand"><b>Viewpoint Compiler</b><span>${escapeHtml(project.settings.aspectRatio)} · ${escapeHtml(project.settings.theme)}</span></div><div class="stage">${visibleScenes.map(renderScene).join("")}</div><div class="controls"><button id="prev" aria-label="Previous scene">←</button><button class="primary" id="play">Play</button><button id="next" aria-label="Next scene">→</button><div class="progress"><i id="bar"></i></div><span class="counter" id="counter"></span></div></main><script>
const project=${safeJson({ id: project.projectId, revision: project.revision, timeline: project.timeline })};const scenes=[...document.querySelectorAll('.scene')];let index=0,timer=null,started=0,raf=0,playing=false;const bar=document.getElementById('bar'),counter=document.getElementById('counter'),play=document.getElementById('play');function animateScene(scene){scene.querySelectorAll('.vnode').forEach((el,i)=>el.animate([{opacity:0,transform:el.getAttribute('transform')+' translate(0 18px)'},{opacity:1,transform:el.getAttribute('transform')}],{duration:480,delay:180+i*360,fill:'both',easing:'cubic-bezier(.2,.8,.2,1)'}));scene.querySelectorAll('.vedge').forEach((el,i)=>{const line=el.querySelector('line'),len=line.getTotalLength();line.animate([{strokeDasharray:len,strokeDashoffset:len},{strokeDasharray:len,strokeDashoffset:0}],{duration:600,delay:520+i*360,fill:'both',easing:'ease-out'})})}function show(next,auto=false){clearTimeout(timer);cancelAnimationFrame(raf);index=(next+scenes.length)%scenes.length;scenes.forEach((s,i)=>s.classList.toggle('active',i===index));counter.textContent=(index+1)+' / '+scenes.length;bar.style.width='0';animateScene(scenes[index]);if(auto||playing){playing=true;play.textContent='Pause';started=performance.now();const duration=Number(scenes[index].dataset.duration)||3200;const tick=now=>{bar.style.width=Math.min(100,(now-started)/duration*100)+'%';if(now-started<duration)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);timer=setTimeout(()=>show(index+1,true),duration)}}play.onclick=()=>{if(playing){playing=false;clearTimeout(timer);cancelAnimationFrame(raf);play.textContent='Play'}else show(index,true)};document.getElementById('prev').onclick=()=>{playing=false;play.textContent='Play';show(index-1)};document.getElementById('next').onclick=()=>{playing=false;play.textContent='Play';show(index+1)};show(0,${project.settings.autoplay});
</script></body></html>`;
}

